# --- Basic Wedding Information ---
title: "The Wedding of Raymond & Phuong Uyen"
description: "Join us to celebrate our wedding on July 17th, 2027"
url: "https://Raymond-Loves-Uyen.github.io" # Replace with your GitHub username
